# Base settings for common model & experiment

experiment_name: "refactor_test_BPR"

# Model settings
model_name: "CA4Rec"
model_arguments:
  hidden_size: 512        # hidden size for multi head attention
  num_attention_heads: 4  # number of heads for multi head attention
  num_hidden_layers: 4    # number of transformer layers
  max_len: 90             # length of input sequence
  dropout_prob: 0.2       # dropout probability
  hidden_act: "gelu"      # Activation function for attention, mlp
  pos_emb: True           # True if using positional embedding
  mask_prob: 0.4          # Input sequence masking probability

  img_noise: True         # Add noise into generated image
  num_mlp_layers: 3       # number of mlp layers
  merge: "mul"            # ways to merge output of bert4rec and image embeddings. One of ["concat", "mul"].

  detail_text: False      # using embedding of detail_text of item
  std: 0.01               # noise std(available if img_noise is True)
  mean: 0                 # noise mean(available if img_noise is True)
  
  gen_img: False          # group by same image description
  


neg_sampling : False      # True if use negative sampling
neg_size : 50             # number of sampling cadidate oiik
neg_sample_size : 5       # number of negative sample


lr: 0.001
epoch: 50
batch_size: 64
weight_decay: 0.001 # weight decay for Adam
num_workers: 0
valid_step: 1 # number of steps to run validation

data_local: False       # True if loading dataset from local directory, else download from huggingface hub
data_repo: "sequential"
dataset: "small"
data_version: "74651f0ea852d5628ecebb39140421ce929da218"

n_cuda: "0"
