# Base settings for common model & experiment
experiment_name: 

# Model settings
model_name: "SASRec"

model_dataset:
  train_dataset: "SASDataset"
  test_dataset: "SASDataset"

model_arguments:
  hidden_size: 256        # hidden size for multi head attention
  num_attention_heads: 4  # number of heads for multi head attention
  num_hidden_layers: 2    # number of transformer layers
  max_len: 70             # length of input sequence
  dropout_prob: 0.2       # dropout probability
  pos_emb: True          # True if using positional embedding
  loss: 'CE'              # ["CE", "BPR"]

 
lr: 0.00001

epoch: 100
batch_size: 256 
shuffle: False       # shuffle dataloader
weight_decay: 0.00001 # weight decay for Adam
num_workers: 8
valid_step: 3 # number of steps to run validation

data_local: False       # True if loading dataset from local directory, else download from huggingface hub
data_repo: "hm_15_core"
dataset: 
data_version: "9d8783944a6c9884913a5fc63e28b407f2210067"

n_cuda: "3"
