# Base settings for common model & experiment
experiment_name: 

# Model settings
model_name: "TMoE"

model_dataset:
  train_dataset: "CLIPCADataset"
  test_dataset: "CLIPCADataset"

model_arguments:
  text_model : "fclip"       # ["sb","fclip", "clip"]
  img_model : "fclip"       # ["fclip", "clip"]
  hidden_size: 128        # hidden size for multi head attention
  num_attention_heads: 2  # number of heads for multi head attention
  num_hidden_layers: 2    # number of transformer layers
  num_enc_layers: 3    # number of encoder attention layers
  num_enc_heads: 2
  num_gen_layers: 2    # number of generator attention layers
  num_gen_heads: 2
  max_len: 70             # length of input sequence
  dropout_prob: 0.2       # dropout probability
  hidden_act: "gelu"      # Activation function for attention, mlp
  pos_emb: True          # True if using positional embedding
  use_linear: True       # if False. use dotpord for scoring
  loss: 'CE'              # ["CE", "BPR"]
  num_experts: 3            # num of experts(modality) (id, img, text)
 
lr: 0.0007
alpha: 0.3 # image loss weight
beta: 0.45 # prompt loss weight       
schedule_rate: 0.03
loss_threshold : 0.2 
alpha_threshold: 0.05
beta_threshold : 0.05

epoch: 70
batch_size: 256 
shuffle: True       # shuffle dataloader
weight_decay: 0.0007 # weight decay for Adam
num_workers: 8
valid_step: 3 # number of steps to run validation

data_local: False       # True if loading dataset from local directory, else download from huggingface hub
data_repo: "amazon_2014_5_core"
dataset: 
data_version: "f3b7f6282a1aa015ce995a19449c5b1779f86c5d"

n_cuda: "2"