# Base settings for common model & experiment
experiment_name: 

# Model settings
model_name: "TMoEC"

model_dataset:
  train_dataset: "CLIPCADataset"
  test_dataset: "CLIPCADataset"

model_arguments:
  text_model : "fclip"       # ["sb","fclip", "clip"]
  img_model : "fclip"       # ["fclip", "clip"]
  hidden_size: 256        # hidden size for multi head attention
  num_attention_heads: 4  # number of heads for multi head attention
  num_hidden_layers: 2    # number of transformer layers
  num_enc_layers: 2    # number of encoder attention layers
  num_enc_heads: 4
  num_gen_layers: 1    # number of generator attention layers
  max_len: 70             # length of input sequence
  dropout_prob: 0.3       # dropout probability
  hidden_act: "gelu"      # Activation function for attention, mlp
  pos_emb: True          # True if using positional embedding
  use_linear: False       # if False. use dotpord for scoring
  loss: 'CE'              # ["CE", "BPR"]
  num_experts: 2            # num of experts(modality) (id, img, text)
  modal_gate: True       # vison text modal gate

lr: 0.0005
alpha: 0.1 # image loss weight
beta: 0.1 # prompt loss weight
theta: 0.05 # cosine loss weight        
rec_weight : 0

schedule_rate: 0
loss_threshold : 0.25 
alpha_threshold: 0
beta_threshold : 0
scheduler : "LambdaLR"


epoch: 100
batch_size: 128 
shuffle: False       # shuffle dataloader
weight_decay: 0.002 # weight decay for Adam
num_workers: 4
valid_step: 3 # number of steps to run validation

data_local: False       # True if loading dataset from local directory, else download from huggingface hub
data_repo: "amazon_2014_5_core" #"hm_15_core", amazon_2014_5_core
dataset: 
data_version: "9915fb18704305458c006fcedc8aec5abf2f1180" #"9d8783944a6c9884913a5fc63e28b407f2210067", 9915fb18704305458c006fcedc8aec5abf2f1180

n_cuda: "3"
