program : main.py
project : MMRec
method: grid
metric: 
    goal: minimize
    name: loss
parameters: 
    dataset:
        value : "small"
    model:
        value : "VBPR"
    sample_size:
        values : [500]
    batch_size: 
        values: [512] 
    epoch: 
        values: [35]
    lr: 
        values: [0.000001, 0.0000005]
    K: 
        values: [35]
    D: 
        values: [45]
    reg_theta: 
        values: [0.00001]
    reg_beta: 
        values: [0.0001]
    reg_e:
        values: [0]
