program : VBPR.py
project : MMRec
method: grid
metric: 
    goal: maximize
    name: train-auc
parameters: 
    batch_size: 
        values: [512] 
    epoch: 
        values: [30]
    lr: 
        values: [0.01, 0.005, 0.001]
    K: 
        values: [25]
    D: 
        values: [25]
    reg_theta: 
        values: [0.1]
    reg_beta: 
        values: [0.1]
    reg_e:
        values: [0]
