program : main.py
project : MMRec
method: grid
metric: 
    goal: minimize
    name: loss
parameters: 
    dataset:
        value : "small"
    model:
        value : "VBPR"
    sample_size:
        values : [500]
    batch_size: 
        values: [512] 
    epoch: 
        values: [70]
    lr: 
        values: [0.0000005]
    K: 
        values: [40]
    D: 
        values: [40]
    vis_weight:
        values: [0.002]
    reg_theta: 
        values: [0.001]
    reg_beta: 
        values: [0.001]
    reg_e:
        values: [0.001]
    
