program : main.py
project : MMRec
method: grid
metric: 
    goal: minimize
    name: loss
parameters: 
    dataset:
        value : "small"
    data_local:
        value : False
    data_version:
        value: "20182752"
    model:
        value : "MF"
    emb_norm:
        value: "None"
    sample_size:
        values : [500]
    batch_size: 
        values: [1024] 
    epoch: 
        values: [100]
    lr: 
        values: [0.0000001]
    K: 
        values: [20, 40]
    D: 
        values: [64]
    reg_theta: 
        values: [0.001, 0.01]
    reg_beta: 
        values: [0.001]
    reg_e:
        values: [0.001]
    
